import chess
import polars as pl
import scipy.stats
import scipy.optimize

import os, sys

sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
import functions
import plotting_helper
import numpy as np


def getMoveData(pgnPaths: list, lichessAnalysis: bool = False, startEval: int = 20, startWDL: list = [205, 614, 181]) -> pl.DataFrame:
    """
    This function reads various data points after each move in the given PGN files
    pgnPaths: list
        List containing the paths to analysed PGN files
    lichessAnalysis: bool
        If this is set, the PGNs are assumed to be analysed by Lichess, containing the [%eval ...] tags
        Otherwise I use my own analysis format
    startEval: int
        Evaluation of the starting position
    startWDL: list
        WDL of the starting position
    return -> pl.DataFrame:
        A ploars DataFrame containing all the data
    """
    gameID = 0

    columns = ["GameID", "Position", "Color", "Move", "Ply", "WhiteElo", "BlackElo", "EvalBefore", "EvalAfter", "WinPBefore", "DrawPBefore", "LossPBefore", "WinPAfter", "DrawPAfter", "LossPAfter", "Result"]
    data = dict()
    for c in columns:
        data[c] = list()

    for pgnPath in pgnPaths:
        with open(pgnPath, 'r') as pgn:
            while game := chess.pgn.read_game(pgn):
                if "WhiteElo" not in game.headers or "BlackElo" not in game.headers:
                    print("No Elo")
                    continue

                ply = 0
                wElo = int(game.headers["WhiteElo"])
                bElo = int(game.headers["BlackElo"])
                result = game.headers["Result"]

                if result not in ["1-0", "1/2-1/2", "0-1"]:
                    print(f"Result not found: {result}")
                    continue

                evalBefore = startEval
                wdlBefore = startWDL

                node = game
                while not node.is_end():
                    board = node.board()
                    node = node.variations[0]
                    ply += 1
                    if node.comment:
                        if lichessAnalysis:
                            if not node.eval():
                                break
                            cp = int(node.eval().white().score(mate_score=10000))
                            wdl = [0, 0, 0]
                        else:
                            wdl, cp = functions.readComment(node, True, True)
                            if wdl is None:
                                wdl = [0, 0, 0]
                        move = node.move
                        data["GameID"].append(gameID)
                        data["Color"].append(board.turn)
                        data["WhiteElo"].append(wElo)
                        data["BlackElo"].append(bElo)
                        data["Result"].append(result)
                        data["Position"].append(board.fen())
                        data["EvalBefore"].append(evalBefore)
                        data["WinPBefore"].append(wdlBefore[0])
                        data["DrawPBefore"].append(wdlBefore[1])
                        data["LossPBefore"].append(wdlBefore[2])
                        data["EvalAfter"].append(cp)
                        data["WinPAfter"].append(wdl[0])
                        data["DrawPAfter"].append(wdl[1])
                        data["LossPAfter"].append(wdl[2])
                        data["Move"].append(move.uci())
                        data["Ply"].append(ply)
                        evalBefore = cp
                        wdlBefore = wdl
                gameID += 1
    df = pl.DataFrame(data)
    return df


def getExpectedScoreDropsPerMove(df: pl.DataFrame, xsdWidth: float = 0.1) -> dict:
    """
    This function calculates the number of different expected score drops for each move in the DataFrame
    df: pl.DataFrame
        DataFrame generated by getMoveData
    xsdWidth: float
        Width of the groups for the expected score drop
    return -> dict
        Indexed by expected score drop, containing the number of moves as values
    """
    drops = dict()
    xsFunction = functions.expectedScore
    for row in df.rows(named=True):
        factor = 1 if row["Color"] else -1
        drop = (xsFunction(row["EvalBefore"]) - xsFunction(row["EvalAfter"])) * factor
        drop = (max(0, drop) + xsdWidth/2) // xsdWidth * xsdWidth

        if drop in drops:
            drops[drop] += 1
        else:
            drops[drop] = 1
        
    return drops


def getExpectedScoreDropsPerGame(df: pl.DataFrame, xsdWidth: float = 0.1, xsFunction = functions.expectedScore, p: float = 1) -> dict:
    """
    This function calculates teh average number of expected score drops per move per game
    df: pl.DataFrame
        DataFrame generated by getMoveData
    xsdWidth: float
        Width of the groups for the average expected score drop
    xsFunction:
        The function used to convert the centipawn evaluations into the expected score
    p: float
        The p-value for the generalised mean
    return -> dict
        Indexed by average expected score drop per game, containing the number of games
    """
    gameDrops = dict()
    gameID = None
    gameAvg = [list(), list()]
    for row in df.rows(named=True):
        if gameID is None:
            gameID = row["GameID"]

        if gameID != row["GameID"]:
            gameID = row["GameID"]
            for i in range(2):
                if len(gameAvg[i]) > 0:
                    avgDrop = scipy.stats.pmean(gameAvg[i], p)
                    avgDrop = (avgDrop + xsdWidth/2) // xsdWidth * xsdWidth
                    if avgDrop in gameDrops:
                        gameDrops[avgDrop] += 1
                    else:
                        gameDrops[avgDrop] = 1

                gameAvg = [list(), list()]

        factor = 1 if row["Color"] else -1
        drop = (xsFunction(row["EvalBefore"]) - xsFunction(row["EvalAfter"])) * factor
        drop = max(0, drop)

        index = max(factor, 0)
        gameAvg[index].append(drop)

    for i in range(2):
        if len(gameAvg[i]) > 0:
            avgDrop = scipy.stats.pmean(gameAvg[i], p)
            avgDrop = (avgDrop + xsdWidth/2) // xsdWidth * xsdWidth
            if avgDrop in gameDrops:
                gameDrops[avgDrop] += 1
            else:
                gameDrops[avgDrop] = 1

    return gameDrops


def getGameEvaluationsFromDF(df: pl.DataFrame) -> list:
    """
    This function extracts the evaluation after each move from the DataFrame and splits them by game. 
    Note that the DataFrame must be grouped into the games and the moves in the games must be in the correct order
    return -> list
        A list containing one list for each game, which contains the evaluation after each move
    """
    gameEvaluations = list()
    evals = list()
    gameID = None
    lastPly = 0
    
    for row in df.rows(named=True):
        if gameID is None:
            gameID = row["GameID"]

        if gameID != row["GameID"]:
            gameEvaluations.append(evals)
            evals = list()
            gameID = row["GameID"]
            lastPly = 0

        if row["Ply"] != lastPly+1:
            print('Skipped moves', lastPly, row["Ply"])

        lastPly = row["Ply"]
        evals.append(row["EvalBefore"])

    gameEvaluations.append(evals)
    return gameEvaluations


def getMeanDensityFromGameEvaluations(gameEvals: list, groupWidth: float = 0.1, expectedScoreFunction = functions.expectedScore, p: float = 1, normalised: float = True) -> dict:
    """
    This gets the density of the mean game expected score loss
    """
    density = dict()
    for gameData in gameEvals:
        if len(gameData) < 2:
            continue
        expectedScoreDropsWhite = [max(0, expectedScoreFunction(gameData[i]) - expectedScoreFunction(gameData[i+1])) for i in range(0, len(gameData)-1, 2)]
        expectedScoreDropsBlack = [max(0, expectedScoreFunction(-gameData[i]) - expectedScoreFunction(-gameData[i+1])) for i in range(1, len(gameData)-1, 2)]
        meanWhite = scipy.stats.pmean(expectedScoreDropsWhite, p)
        meanBlack = scipy.stats.pmean(expectedScoreDropsBlack, p)

        meanWhite = float((meanWhite + groupWidth/2) // groupWidth * groupWidth)
        meanBlack = float((meanBlack + groupWidth/2) // groupWidth * groupWidth)

        for m in [meanWhite, meanBlack]:
            if m not in density:
                density[m] = 1
            else:
                density[m] += 1

    density = dict(sorted(density.items()))

    if normalised:
        return {k: v/sum(list(density.values())) for k, v in density.items()}
    return density


def getDistributionFromDensity(density: dict) -> dict:
    return {k: 1-sum(list(density.values())[:i+1]) for i, k in enumerate(list(density.keys()))}


def lichessAccuracy(expectedScoreDrop: float):
    return functions.accuracy(expectedScoreDrop, 0)/100


def gameAccuracy(expectedScoreDrop: float, sigma: float, offset: float) -> float:
    """
    if expectedScoreDrop <= offset:
        return 1
    """

    return np.exp(-(expectedScoreDrop-offset)**2/(2*sigma**2))


def fitGameAccuracyToData(distribution: dict, accuracyFunction):
    return scipy.optimize.curve_fit(accuracyFunction, list(distribution.keys()), list(distribution.values()))


def filterDFByRating(minRating: int = 0, maxRating: int = 3000, maxRatingDiff: int = 3000) -> pl.DataFrame:
    """
    This function filters a given polars DataFrame and returns a new DataFrame with the filters applied
    """
    ndf = df.filter(pl.col("WhiteElo") >= minRating,
                    pl.col("WhiteElo") <= maxRating,
                    pl.col("BlackElo") >= minRating,
                    pl.col("WhiteElo") <= maxRating,
                    abs(pl.col("WhiteElo")-pl.col("BlackElo")) <= maxRatingDiff)

    return ndf


if __name__ == '__main__':
    carlsen = ['../out/carlsenClassicalAnalysed.pgn']
    pgns = ['../out/games/2700games2023-out.pgn', '../out/games/olympiad2024-out.pgn', '../out/games/grenkeOpen2024.pgn', '../out/games/wijkMasters2024-5000-30.pgn', '../out/games/shenzhen-5000-30.pgn', '../out/games/norwayChessClassical.pgn', '../out/games/candidates2024-WDL+CP.pgn', '../out/games/tepe-sigeman-5000-30.pgn', '../out/games/gukesh2022-out.pgn', '../out/games/Norway2021-classical.pgn', '../out/games/arjun_open-5000-30.pgn', '../out/games/bundesliga2500-out.pgn', '../out/games/candidates2026_analysed.pgn', '../out/games/candidatesW2026_analysed.pgn', '../out/games/grandSwiss2025Analysed.pgn']
    testScores = [0, 50, 75, 100, 125, 150, 175, 200, 225, 250]
    testScores2 = [0, 0, 0, 0, 0, 0, 0, 0, 0, 250]
    testScores = [20, -20, 40, -30, -40, -60, -30, -30, -20, -30, 0, 0, 50, 20, 110, 140, 370, 200, 280, 180, 240, 100, 100, -10, 10, 20, 120, 70, 340, 10, 300, 100, 170, 180, 150, 160, 190, -80, 0, 0, 0, -30, 20, -50, 140, 30, 40, -140, -80, -160, -200, -180, -120, -90, -20, -150, -140, -120, -40, -260, -240, -260, -260, -570, -560, -550, -520, -510, -450, -470, -440, -420, -370, -420, -380, -430, -450, -430, -430, -490, -480, -500, -440]
    print(functions.lichessGameAccuracy(testScores))
    # df = getMoveData(pgns)
    # df.write_parquet('../out/classicalDF.parquet')
    df = pl.read_parquet('../out/classicalDF.parquet')
    ndf = filterDFByRating(2500, 2520)
    with pl.Config(tbl_cols=-1):
        print(ndf)
    evals = getGameEvaluationsFromDF(df)
    groupWidth = 0.1
    drops = getExpectedScoreDropsPerMove(df, xsdWidth=groupWidth)
    drops = dict(sorted(drops.items()))
    total = sum(list(drops.values()))
    drops = {k: v/total for k, v in drops.items()}
    distributionFunction = {k: 1-sum(list(drops.values())[:i+1]) for i, k in enumerate(list(drops.keys()))}
    density = getMeanDensityFromGameEvaluations(evals)
    dist = getDistributionFromDensity(density)
    params, x = fitGameAccuracyToData(dist, gameAccuracy)
    plotting_helper.plotLineChart([list(dist.keys())], [list(dist.values())], 'XS drop', 'Percentile', 'Fitting the curve', ['Data', 'Function'], refFunction=lambda d: gameAccuracy(d, params[0], params[1]))
    # plotting_helper.plotDistribution(list(density.keys()), list(density.values()), groupWidth, 'Expected score drop', 'Number of games', 'Avg expected score drop')
    """
    gameDrops = getExpectedScoreDropsPerGame(df, groupWidth)
    gameDrops2 = getExpectedScoreDropsPerGame(df, groupWidth, p=2)
    gameDrops3 = getExpectedScoreDropsPerGame(df, groupWidth, p=3)
    gameDrops1 = getExpectedScoreDropsPerGame(df, groupWidth, p=0)
    # plotting_helper.plotLineChart([list(distributionFunction.keys())], [list(distributionFunction.values())], 'Expected score drop', 'Relative number of moves', 'Move accuracy', legend=['My data', 'Lichess'], refFunction=lichessAccuracy)
    # plotting_helper.plotDistribution(list(drops.keys())[1:], list(drops.values())[1:], groupWidth, 'Expected score drop', 'Number of moves', 'Expected score drops', xMax=80, referenceFunction=lichessAccuracy, logScale=True)
    # plotting_helper.plotDistribution(list(gameDrops.keys()), list(gameDrops.values()), groupWidth, 'Expected score drop', 'Number of games', 'Avg expected score drop')
    xVals = [list(gameDrops.keys()), list(gameDrops2.keys()), list(gameDrops3.keys())] #, list(gameDrops1.keys())]
    yVals = [list(gameDrops.values()), list(gameDrops2.values()), list(gameDrops3.values())] #, list(gameDrops1.values())]
    plotting_helper.plotMultipleDistributions(xVals, yVals, groupWidth, 'Expected score drop', 'Number of games', 'Avg expected score drop', xMax=25, legend=['p=1', 'p=2', 'p=3', 'p=-1'])
    """
