import chess
import polars as pl
import scipy.stats
from scipy.stats import beta
import scipy.optimize
import statistics

import os, sys

sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
import functions
import plotting_helper
import numpy as np


def getMoveData(pgnPaths: list, lichessAnalysis: bool = False, startEval: int = 20, startWDL: list = [205, 614, 181]) -> pl.DataFrame:
    """
    This function reads various data points after each move in the given PGN files
    pgnPaths: list
        List containing the paths to analysed PGN files
    lichessAnalysis: bool
        If this is set, the PGNs are assumed to be analysed by Lichess, containing the [%eval ...] tags
        Otherwise I use my own analysis format
    startEval: int
        Evaluation of the starting position
    startWDL: list
        WDL of the starting position
    return -> pl.DataFrame:
        A ploars DataFrame containing all the data
    """
    gameID = 0

    columns = ["GameID", "Position", "Color", "Move", "Ply", "WhiteElo", "BlackElo", "EvalBefore", "EvalAfter", "WinPBefore", "DrawPBefore", "LossPBefore", "WinPAfter", "DrawPAfter", "LossPAfter", "Result"]
    data = dict()
    for c in columns:
        data[c] = list()

    for pgnPath in pgnPaths:
        with open(pgnPath, 'r') as pgn:
            while game := chess.pgn.read_game(pgn):
                if "WhiteElo" not in game.headers or "BlackElo" not in game.headers:
                    if "White" in game.headers and "Black" in game.headers and "Date" in game.headers:
                        print(f'No Elo in {game.headers["White"]}-{game.headers["Black"]}, game.headers["Date"]')
                    else:
                        print('No names')
                    continue

                ply = 0
                wElo = int(game.headers["WhiteElo"])
                bElo = int(game.headers["BlackElo"])
                result = game.headers["Result"]

                if result not in ["1-0", "1/2-1/2", "0-1"]:
                    print(f"Result not found: {result}")
                    continue

                evalBefore = startEval
                wdlBefore = startWDL

                node = game
                while not node.is_end():
                    board = node.board()
                    node = node.variations[0]
                    ply += 1
                    if node.comment:
                        if lichessAnalysis:
                            if not node.eval():
                                print(f'No evaluation found in {game.headers["White"]}-{game.headers["Black"]}, {game.headers["Date"]} on ply {ply}')
                                break
                            cp = int(node.eval().white().score(mate_score=10000))
                            wdl = [0, 0, 0]
                        else:
                            wdl, cp = functions.readComment(node, True, True)
                            if wdl is None:
                                wdl = [0, 0, 0]
                            if cp is None:
                                print(f'No evaluation found in {game.headers["White"]}-{game.headers["Black"]}, {game.headers["Date"]} on ply {ply}')
                        move = node.move
                        data["GameID"].append(gameID)
                        data["Color"].append(board.turn)
                        data["WhiteElo"].append(wElo)
                        data["BlackElo"].append(bElo)
                        data["Result"].append(result)
                        data["Position"].append(board.fen())
                        data["EvalBefore"].append(evalBefore)
                        data["WinPBefore"].append(wdlBefore[0])
                        data["DrawPBefore"].append(wdlBefore[1])
                        data["LossPBefore"].append(wdlBefore[2])
                        data["EvalAfter"].append(cp)
                        data["WinPAfter"].append(wdl[0])
                        data["DrawPAfter"].append(wdl[1])
                        data["LossPAfter"].append(wdl[2])
                        data["Move"].append(move.uci())
                        data["Ply"].append(ply)
                        evalBefore = cp
                        wdlBefore = wdl
                    elif not node.is_end():
                        print(f'No comment found in {game.headers["White"]}-{game.headers["Black"]}, {game.headers["Date"]} on ply {ply}')
                gameID += 1
    df = pl.DataFrame(data)
    return df


def getExpectedScoreDropsPerMove(df: pl.DataFrame, xsdWidth: float = 0.1, excludePerfectMoves: bool = False) -> dict:
    """
    This function calculates the number of different expected score drops for each move in the DataFrame
    df: pl.DataFrame
        DataFrame generated by getMoveData
    xsdWidth: float
        Width of the groups for the expected score drop
    excludePerfectMoves: bool
        If this is true, perfect moves (moves with a drop of <= 0) won't be counted
        This is because over 30% of GM moves are perfect and skew the data
    return -> dict
        Indexed by expected score drop, containing the number of moves as values
    """
    drops = dict()
    xsFunction = functions.expectedScore
    for row in df.rows(named=True):
        factor = 1 if row["Color"] else -1
        drop = (xsFunction(row["EvalBefore"]) - xsFunction(row["EvalAfter"])) * factor
        if excludePerfectMoves and drop <= 0:
            continue

        drop = (max(0, drop) + xsdWidth/2) // xsdWidth * xsdWidth

        if drop in drops:
            drops[drop] += 1
        else:
            drops[drop] = 1
        
    return dict(sorted(drops.items()))


def getExpectedScoreDropsPerGame(df: pl.DataFrame, xsdWidth: float = 0.1, xsFunction = functions.expectedScore, p: float = 1) -> dict:
    """
    This function calculates teh average number of expected score drops per move per game
    df: pl.DataFrame
        DataFrame generated by getMoveData
    xsdWidth: float
        Width of the groups for the average expected score drop
    xsFunction:
        The function used to convert the centipawn evaluations into the expected score
    p: float
        The p-value for the generalised mean
    return -> dict
        Indexed by average expected score drop per game, containing the number of games
    """
    gameDrops = dict()
    gameID = None
    gameAvg = [list(), list()]
    for row in df.rows(named=True):
        if gameID is None:
            gameID = row["GameID"]

        if gameID != row["GameID"]:
            gameID = row["GameID"]
            for i in range(2):
                if len(gameAvg[i]) > 0:
                    avgDrop = scipy.stats.pmean(gameAvg[i], p)
                    avgDrop = (avgDrop + xsdWidth/2) // xsdWidth * xsdWidth
                    if avgDrop in gameDrops:
                        gameDrops[avgDrop] += 1
                    else:
                        gameDrops[avgDrop] = 1

                gameAvg = [list(), list()]

        factor = 1 if row["Color"] else -1
        drop = (xsFunction(row["EvalBefore"]) - xsFunction(row["EvalAfter"])) * factor
        drop = max(0, drop)

        index = 1-max(factor, 0)
        gameAvg[index].append(drop)

    for i in range(2):
        if len(gameAvg[i]) > 0:
            avgDrop = scipy.stats.pmean(gameAvg[i], p)
            avgDrop = (avgDrop + xsdWidth/2) // xsdWidth * xsdWidth
            if avgDrop in gameDrops:
                gameDrops[avgDrop] += 1
            else:
                gameDrops[avgDrop] = 1

    return gameDrops


def getGameEvaluationsFromDF(df: pl.DataFrame) -> list:
    """
    This function extracts the evaluation after each move from the DataFrame and splits them by game. 
    Note that the DataFrame must be grouped into the games and the moves in the games must be in the correct order
    return -> list
        A list containing one list for each game, which contains the evaluation after each move
    """
    gameEvaluations = list()
    evals = list()
    gameID = None
    lastPly = 0
    finalEval = None
    
    for row in df.rows(named=True):
        if gameID is None:
            gameID = row["GameID"]

        if gameID != row["GameID"]:
            evals.append(finalEval)
            gameEvaluations.append(evals)
            evals = list()
            gameID = row["GameID"]
            lastPly = 0

        if row["Ply"] != lastPly+1:
            print('Skipped moves', lastPly, row["Ply"])

        lastPly = row["Ply"]
        evals.append(row["EvalBefore"])
        finalEval = row["EvalAfter"]

    evals.append(finalEval)
    gameEvaluations.append(evals)

    return gameEvaluations


def calculateGeneralisedMean(evaluations: list, expectedScoreFunction=functions.expectedScore, p: float = 1) -> tuple:
    if len(evaluations) < 3:
        return None

    expectedScoreDropsWhite, expectedScoreDropsBlack = getExpectedScoreDropsFromEvaluations(evaluations, expectedScoreFunction)

    if p < 0:
        expectedScoreDropsWhite = [max(0.1, xsDrop) for xsDrop in expectedScoreDropsWhite]
        expectedScoreDropsBlack = [max(0.1, xsDrop) for xsDrop in expectedScoreDropsBlack]

    whiteMean = scipy.stats.pmean(expectedScoreDropsWhite, p)
    blackMean = scipy.stats.pmean(expectedScoreDropsBlack, p)

    """
    print(f'p={p}')
    print(round(whiteMean, 3), round(blackMean, 3))
    print(round(sum(expectedScoreDropsWhite), 3), round(sum(expectedScoreDropsBlack), 3))
    print([round(xs, 2) for xs in expectedScoreDropsWhite])
    print([round(xs, 2) for xs in expectedScoreDropsBlack])
    """

    return (float(whiteMean), float(blackMean))


def getMeanDensityFromGameEvaluations(gameEvals: list, groupWidth: float = 0.1, meanFunction=calculateGeneralisedMean, normalised: float = True) -> dict:
    """
    This gets the density of the mean game expected score loss
    gameEvals: list
        A list containing a list of eavluations for each game
    groupWidth: float
        The means will get grouped together, this determines the size of the individual groups
    meanFunction:
        The function used to calculate the mean. It has to return a tuple with the white and black mean
    normalised: bool
        If this is set, the sum of all means will be 1
        Otherwise, it will be the total number of games
    return -> dict
        Dictionary indexed by the mean expected score drop for each game, containing the (relative) number of games with this drop
    """
    density = dict()
    for gameData in gameEvals:
        if len(gameData) < 3:
            continue

        for mean in meanFunction(gameData):
            mean = float((mean + groupWidth/2) // groupWidth * groupWidth)

            if mean not in density:
                density[mean] = 1
            else:
                density[mean] += 1

    density = dict(sorted(density.items()))

    if normalised:
        return {k: v/sum(list(density.values())) for k, v in density.items()}

    return density


def getExpectedScoreDropsFromEvaluations(evals: list, expectedScoreFunction = functions.expectedScore) -> tuple:
    """
    This function calculates the expected score drops for both colors from a list of evaluations
    evals: list
        The evaluations before each move
    expectedScoreFunction
        The functions to calculate the expected score from an evaluation
    return -> tuple(list(), list())
        The expected score drops for white and black
    """
    expectedScoreDropsWhite = [max(0, expectedScoreFunction(evals[i]) - expectedScoreFunction(evals[i+1])) for i in range(0, len(evals)-1, 2)]
    expectedScoreDropsBlack = [max(0, expectedScoreFunction(-evals[i]) - expectedScoreFunction(-evals[i+1])) for i in range(1, len(evals)-1, 2)]

    return (expectedScoreDropsWhite, expectedScoreDropsBlack)


def getDistributionFromDensity(density: dict, addZero: bool = False) -> dict:
    """
    This calculates the distribution function, given a normalised density as a dict
    """
    if addZero and 0 not in density:
        density[0] = 0
        density = dict(sorted(density.items()))
    return {k: sum(list(density.values())[:i+1]) for i, k in enumerate(list(density.keys()))}


def lichessAccuracy(expectedScoreDrop: float):
    return functions.accuracy(expectedScoreDrop, 0)/100


def moveAccuracy(expectedScoreDrop: float, k: float, l: float) -> float:
    return 1-beta.cdf(expectedScoreDrop/100, k, l)
    return 100**(k*expectedScoreDrop)
    # return np.minimum(103.1668100711649 * np.exp(k * expectedScoreDrop) - 3.166924740191411, 100) / 100


def mixtureDistribution(expectedScoreDrop: float, a1: float, b1: float, a2: float, b2: float):
    return 1 - (0.5 * beta.cdf(expectedScoreDrop/100, a1, b1) + 0.5 * beta.cdf(expectedScoreDrop/100, a2, b2))


def gameAccuracy(expectedScoreDrop: float, sigma: float, offset: float) -> float:
    x = np.maximum(expectedScoreDrop - offset, 0)

    return np.exp(-(x**2)/(2*sigma**2))


def fitFunctionToDistribution(distribution: dict, function, bounds: tuple = None):
    if bounds is None:
        return scipy.optimize.curve_fit(function, list(distribution.keys()), [1-v for v in distribution.values()])

    return scipy.optimize.curve_fit(function, list(distribution.keys()), [1-v for v in distribution.values()], bounds=bounds)


def calculateGameAccuracies(evals: list, expectedScoreFunction = functions.expectedScore, gameAccuracyFunction = lambda x: gameAccuracy(x, 1.5, 0.2), p: float = 1, scale: float = 100) -> tuple:
    """
    This function calculates the accuracies for both colors in a game
    evals: list
        List of centipawn evaluations
    expectedScoreFunction
        The function used to convert the centipawns into an expected score
    gameAccuracyFunction
        The function used to calculate the accuracy of a game
    p: float
        The p-value for the generalised mean
    scale: float
        A value to rescale the accuracy
    return -> tuple
        (whiteAccuracy, blackAccuracy)
    """
    expectedScoreDropsWhite, expectedScoreDropsBlack = getExpectedScoreDropsFromEvaluations(evals, expectedScoreFunction)

    meanWhite = scipy.stats.pmean(expectedScoreDropsWhite, p)
    meanBlack = scipy.stats.pmean(expectedScoreDropsBlack, p)

    return (float(gameAccuracyFunction(meanWhite)) * scale, float(gameAccuracyFunction(meanBlack)) * scale)


def filterDFByRating(df: pl.DataFrame, minRating: int = 0, maxRating: int = 3000, maxRatingDiff: int = 3000, minPly: int = 0) -> pl.DataFrame:
    """
    This function filters a given polars DataFrame and returns a new DataFrame with the filters applied
    """
    ndf = df.filter(pl.col("WhiteElo") >= minRating,
                    pl.col("WhiteElo") <= maxRating,
                    pl.col("BlackElo") >= minRating,
                    pl.col("WhiteElo") <= maxRating,
                    abs(pl.col("WhiteElo")-pl.col("BlackElo")) <= maxRatingDiff, 
                    pl.col("Ply") >= minPly)

    return ndf


def removeShortGames(df: pl.DataFrame, maxMoves: int, removeDecisiveGames: bool = False) -> pl.DataFrame:
    """
    This function filters out all short games from a data frame
    """
    gameIDs = list()
    gameID = None
    lastPly = 0
    for row in df.rows(named=True):
        if gameID is None:
            gameID = row["GameID"]

        if gameID != row["GameID"]:
            if lastPly <= 2*maxMoves:
                if removeDecisiveGames:
                    gameIDs.append(gameID)
                elif row["Result"] == "1/2-1/2":
                    gameIDs.append(gameID)

            gameID = row["GameID"]
            lastPly = 1

        lastPly += 1

    ndf = df.clone()
    for gameID in gameIDs:
        ndf = ndf.remove(pl.col("GameID") .eq(gameID))

    return ndf


def calculateVolatilityWeightedMean(evaluations: list, expectedScoreFunction=functions.expectedScore, moveAccuracyFunction=None, minWindowSize: int = 2, maxWindowSize: int = 8, nWindows: int = 10, minVolatility: float = 0.5, maxVolatility: float = 12) -> tuple:
    """
    This calculates the volatility weighted mean of the move accuracy (or expected score drops) for both colors
    evaluations: list
        The evaluations of a game
    expectedScoreFunction
        The function used to calculate the expected score
    moveAccuracyFunction
        The function used to calculate the move accuracy
        If no function is given, the expected score drop will be used as move accuracy
    minWindowSize, maxWindowSize, nWindows:
        Minimum and maximimum window size and the number of windows (if this doesn't lead to window sizes outside of the ranges)
    minVolatility, maxVolatility:
        Lower and upper bounds for the volatility
    return -> tuple
        (whiteMean, blackMean)
    """
    expectedScores = [expectedScoreFunction(evaluation) for evaluation in evaluations]
    windowSize = int(len(expectedScores) / nWindows)
    windowSize = min(maxWindowSize, max(minWindowSize, windowSize))

    prefixCount = windowSize - 2
    windows = [expectedScores[:windowSize] for _ in range(prefixCount)]
    windows.extend([expectedScores[i:i+windowSize] for i in range(len(expectedScores) - windowSize + 1)])

    volatilities = [max(minVolatility, min(maxVolatility, statistics.pstdev(window))) for window in windows]

    accuraciesWhite = list()
    accuraciesBlack = list()

    for i in range(len(expectedScores)-1):
        xsBefore = expectedScores[i]
        xsAfter = expectedScores[i+1]
        volatility = volatilities[i]

        if i % 2 == 0:
            xsDrop = max(0, xsBefore - xsAfter)
            if moveAccuracyFunction is not None:
                accuraciesWhite.append((moveAccuracyFunction(xsDrop), volatility))
            else:
                accuraciesWhite.append((xsDrop, volatility))
        else:
            xsDrop = max(0, xsAfter - xsBefore)
            if moveAccuracyFunction is not None:
                accuraciesBlack.append((moveAccuracyFunction(xsDrop), volatility))
            else:
                accuraciesBlack.append((xsDrop, volatility))

    weightedMeanWhite = sum([accuracy * volatility for accuracy, volatility in accuraciesWhite]) / sum([volatility for _, volatility in accuraciesWhite])
    weightedMeanBlack = sum([accuracy * volatility for accuracy, volatility in accuraciesBlack]) / sum([volatility for _, volatility in accuraciesBlack])

    return (weightedMeanWhite, weightedMeanBlack)


def testAccuracyFunctions(pgnPaths: list, accuracyFunctions: list, lichessAnalysis: bool = True, plotEvaluations: bool = True, functionNames: list = None):
    """
    This is a function to test different accuracy function
    pgnPaths: list
        List of PGN paths to the games to look at
    accuracyFunctions: list
        A list of the different accuracy functions. 
        Each function should just take the evaluations of a game as an input
    lichessAnalysis: bool
        If this is true, the PGNs are assumed to be analysed by Lichess
    functionNames: list
        Names for functions so that the output becomes more legible
    plotEvaluations: bool
        If this is true, a plot with the evaluations of all games will be shown in the end
    """
    evaluations = list()
    for pgnPath in pgnPaths:
        evals = functions.getEvalsFromPGN(pgnPath, lichessAnalysis=lichessAnalysis)
        evaluations.append(evals)

        print(evals)

        print(pgnPath.split('/')[-1][:-4])
        for i, accFunction in enumerate(accuracyFunctions):
            if functionNames:
                print(functionNames[i], accFunction(evals))
            else:
                print(accFunction(evals))

    if plotEvaluations:
        plotting_helper.plotLineChart([list(range(1, len(evals)+1)) for evals in evaluations], evaluations, 'Move number', 'Game evaluation', 'Game evaluations', [pgnPath.split('/')[-1][:-4] for pgnPath in pgnPaths])


def calculateAccuracyFromDistribution(evals: list, distribution: dict, meanFunction) -> tuple:
    whiteMean, blackMean = meanFunction(evals)
    distribution = {k: 1-v for k, v in distribution.items()}
    whiteAcc = 0
    blackAcc = 0

    for i, (k, v) in enumerate(list(distribution.items())[:-1]):
        k1 = list(distribution.keys())[i+1]
        if k <= whiteMean < k1:
            interpolation = (whiteMean - k) / (k1 - k)
            whiteAcc = distribution[k] + (distribution[k1] - distribution[k])*interpolation
        if k <= blackMean < k1:
            interpolation = (blackMean - k) / (k1 - k)
            blackAcc = distribution[k] + (distribution[k1] - distribution[k])*interpolation

    return (float(whiteAcc) * 100, float(blackAcc) * 100)


if __name__ == '__main__':
    # Basic testing
    pgn = ['../out/games/Carlsen-Keymer_2026.pgn']
    # pgn = ['../resources/Caruana-Wei.pgn']
    carlsen = ['../out/carlsenClassicalAnalysed.pgn']
    pgns = ['../out/games/2700games2023-out.pgn', '../out/games/olympiad2024-out.pgn', '../out/games/grenkeOpen2024.pgn', '../out/games/wijkMasters2024-5000-30.pgn', '../out/games/shenzhen-5000-30.pgn', '../out/games/norwayChessClassical.pgn', '../out/games/candidates2024-WDL+CP.pgn', '../out/games/tepe-sigeman-5000-30.pgn', '../out/games/gukesh2022-out.pgn', '../out/games/Norway2021-classical.pgn', '../out/games/arjun_open-5000-30.pgn', '../out/games/bundesliga2500-out.pgn', '../out/games/candidates2026_analysed.pgn', '../out/games/candidatesW2026_analysed.pgn', '../out/games/grandSwiss2025Analysed.pgn']

    accuracyTestPGNs = ['../out/games/Esipenko-Caruana_2026.pgn', '../out/games/Bluebaum-Giri_2026.pgn', '../out/games/Caruana-Wei_2026.pgn', '../out/games/Nakamura-Caruana_2026.pgn', '../out/games/Bluebaum-Sindarov_2026.pgn', '../out/games/Pragg-Bluebaum_2026.pgn', '../out/games/Wei-Giri_2026.pgn', '../out/games/Carlsen-Keymer_2026.pgn']
    accuracyTestPGNs = ['../out/games/Bluebaum-Sindarov_2026.pgn', '../resources/messyBlitzGame.pgn']
    # df = getMoveData(pgns)
    # df.write_parquet('../out/classicalDF.parquet')
    df = pl.read_parquet('../out/classicalDF.parquet')

    ndf = filterDFByRating(df, 2500)
    # ndf2 = removeShortGames(ndf, 25, removeDecisiveGames=False)
    """
    with pl.Config(tbl_cols=-1):
        print(ndf)
    """

    groupWidth = 0.05
    
    """
    evals = functions.getEvalsFromPGN(accuracyTestPGNs[0], lichessAnalysis=True, startEval=15)
    print(calculateGeneralisedMean(evals, p=1))
    print(calculateGeneralisedMean(evals, p=2))
    """


    # evals = functions.getEvalsFromPGN(pgn[0], lichessAnalysis=True)
    # wxs, bxs = getExpectedScoreDropsFromEvaluations(evals, lambda x: x)
    # print(calculateVolatilityWeightedMean(evals))
    # print(getMeanDensityFromGameEvaluations([evals]))

    # Comparing different accuracy functions
    meanFunctions = [calculateVolatilityWeightedMean, lambda x: calculateGeneralisedMean(x, p=-1), lambda x: calculateGeneralisedMean(x, p=0.5), lambda x: calculateGeneralisedMean(x, p=1), lambda x: calculateGeneralisedMean(x, p=2)]
    accuracyFunctions = [functions.lichessGameAccuracy]
    referenceEvals = getGameEvaluationsFromDF(ndf)
    functionNames = ['Lichess', 'Weighted mean xs loss', 'p=-1', 'p=0.5', 'p=1', 'p=2']
    for i, meanFunction in enumerate(meanFunctions):
        density = getMeanDensityFromGameEvaluations(referenceEvals, meanFunction=meanFunction, groupWidth=groupWidth)
        distribution = getDistributionFromDensity(density, addZero=True)
        # plotting_helper.plotDistribution(list(density.keys()), list(density.values()), groupWidth, 'Expected score drop', 'Number of games', f'Avg expected score drop {functionNames[i+1]}')
        accuracyFunction = lambda x, d=distribution, m=meanFunction: calculateAccuracyFromDistribution(x, d, m)
        accuracyFunctions.append(accuracyFunction)

    testAccuracyFunctions(accuracyTestPGNs, accuracyFunctions, plotEvaluations=False, functionNames=functionNames, lichessAnalysis=True)

    # Move accuracy function
    """
    moveDensity = getExpectedScoreDropsPerMove(ndf, groupWidth, excludePerfectMoves=True)
    normalisedDensity = {k: v/sum(list(moveDensity.values())) for k, v in moveDensity.items()}
    normalisedDensity[-groupWidth] = 0
    normalisedDensity = dict(sorted({k+groupWidth: v for k, v in normalisedDensity.items()}.items()))
    print(normalisedDensity)
    distribution = getDistributionFromDensity(normalisedDensity)
    # params, pcov = fitFunctionToDistribution(distribution, moveAccuracy)
    params, pcov = fitFunctionToDistribution(distribution, mixtureDistribution)
    print(params, pcov)
    # plotting_helper.plotLineChart([list(distribution.keys())], [[1-v for v in distribution.values()]], 'XS drop', 'Percentile', 'Fitting the curve', ['Data', 'Function'], refFunction=lambda d: moveAccuracy(d, *params), xMin=0, xMax=20)
    plotting_helper.plotLineChart([list(distribution.keys())], [[1-v for v in distribution.values()]], 'XS drop', 'Percentile', 'Fitting the curve', ['Data', 'Function'], refFunction=lambda d: mixtureDistribution(d, *params), xMin=0, xMax=20)
    evals = functions.getEvalsFromPGN(pgn[0], lichessAnalysis=True)
    print(functions.lichessGameAccuracy(evals))
    print(functions.lichessGameAccuracy(evals, expectedScoreFunction=functions.expectedScore, moveAccuracyFunction=lambda a, b: moveAccuracy(a-b, *params)*100))
    print(calculateGameAccuracies(evals)) #, gameAccuracyFunction=lambda x: gameAccuracy(x, 0.83, 0), p=0.5))
    """

    # Getting parameters for a game accuracy function
    """
    p = 1
    pMean = lambda x: calculateGeneralisedMean(x, p=p)
    weightedMean = lambda x: calculateVolatilityWeightedMean(x)
    referenceEvals = getGameEvaluationsFromDF(ndf)
    density = getMeanDensityFromGameEvaluations(referenceEvals, meanFunction=weightedMean, groupWidth=groupWidth)
    dist = getDistributionFromDensity(density, addZero=True)
    print(dist)
    params, x = fitFunctionToDistribution(dist, gameAccuracy, bounds=(0, 10))
    print(params)
    plotting_helper.plotLineChart([list(dist.keys())], [[1-v for v in dist.values()]], 'XS drop', 'Percentile', 'Fitting the curve', ['Data', 'Function'], refFunction=lambda d: gameAccuracy(d, *params), xMin=0)
    """
    # plotting_helper.plotDistribution(list(density.keys()), list(density.values()), groupWidth, 'Expected score drop', 'Number of games', 'Avg expected score drop')
    """
    gameDrops = getExpectedScoreDropsPerGame(df, groupWidth)
    gameDrops2 = getExpectedScoreDropsPerGame(df, groupWidth, p=2)
    gameDrops3 = getExpectedScoreDropsPerGame(df, groupWidth, p=3)
    gameDrops1 = getExpectedScoreDropsPerGame(df, groupWidth, p=0)
    # plotting_helper.plotLineChart([list(distributionFunction.keys())], [list(distributionFunction.values())], 'Expected score drop', 'Relative number of moves', 'Move accuracy', legend=['My data', 'Lichess'], refFunction=lichessAccuracy)
    # plotting_helper.plotDistribution(list(drops.keys())[1:], list(drops.values())[1:], groupWidth, 'Expected score drop', 'Number of moves', 'Expected score drops', xMax=80, referenceFunction=lichessAccuracy, logScale=True)
    # plotting_helper.plotDistribution(list(gameDrops.keys()), list(gameDrops.values()), groupWidth, 'Expected score drop', 'Number of games', 'Avg expected score drop')
    xVals = [list(gameDrops.keys()), list(gameDrops2.keys()), list(gameDrops3.keys())] #, list(gameDrops1.keys())]
    yVals = [list(gameDrops.values()), list(gameDrops2.values()), list(gameDrops3.values())] #, list(gameDrops1.values())]
    plotting_helper.plotMultipleDistributions(xVals, yVals, groupWidth, 'Expected score drop', 'Number of games', 'Avg expected score drop', xMax=25, legend=['p=1', 'p=2', 'p=3', 'p=-1'])
    """
