import chess
import polars as pl


import os, sys

sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
import functions
import plotting_helper


def getMoveData(pgnPaths: list, lichessAnalysis: bool = False, startEval: int = 20, startWDL: list = [205, 614, 181]) -> pl.DataFrame:
    """
    This function reads various data points after each move in the given PGN files
    pgnPaths: list
        List containing the paths to analysed PGN files
    lichessAnalysis: bool
        If this is set, the PGNs are assumed to be analysed by Lichess, containing the [%eval ...] tags
        Otherwise I use my own analysis format
    startEval: int
        Evaluation of the starting position
    startWDL: list
        WDL of the starting position
    return -> pl.DataFrame:
        A ploars DataFrame containing all the data
    """
    gameID = 0

    columns = ["GameID", "Position", "Color", "Move", "MoveNr", "WhiteElo", "BlackElo", "EvalBefore", "EvalAfter", "WinPBefore", "DrawPBefore", "LossPBefore", "WinPAfter", "DrawPAfter", "LossPAfter", "Result"]
    data = dict()
    for c in columns:
        data[c] = list()

    for pgnPath in pgnPaths:
        with open(pgnPath, 'r') as pgn:
            while game := chess.pgn.read_game(pgn):
                if "WhiteElo" not in game.headers or "BlackElo" not in game.headers:
                    print("No Elo")
                    continue

                ply = 1
                wElo = int(game.headers["WhiteElo"])
                bElo = int(game.headers["BlackElo"])
                result = game.headers["Result"]

                if result not in ["1-0", "1/2-1/2", "0-1"]:
                    print(f"Result not found: {result}")
                    continue

                evalBefore = startEval
                wdlBefore = startWDL

                node = game
                while not node.is_end():
                    board = node.board()
                    node = node.variations[0]
                    ply += 1
                    if node.comment:
                        if lichessAnalysis:
                            if not node.eval():
                                break
                            cp = int(node.eval().white().score(mate_score=10000))
                            wdl = [0, 0, 0]
                        else:
                            wdl, cp = functions.readComment(node, True, True)
                            if wdl is None:
                                wdl = [0, 0, 0]
                        move = node.move
                        data["GameID"].append(gameID)
                        data["Color"].append(board.turn)
                        data["WhiteElo"].append(wElo)
                        data["BlackElo"].append(bElo)
                        data["Result"].append(result)
                        data["Position"].append(board.fen())
                        data["EvalBefore"].append(evalBefore)
                        data["WinPBefore"].append(wdlBefore[0])
                        data["DrawPBefore"].append(wdlBefore[1])
                        data["LossPBefore"].append(wdlBefore[2])
                        data["EvalAfter"].append(cp)
                        data["WinPAfter"].append(wdl[0])
                        data["DrawPAfter"].append(wdl[1])
                        data["LossPAfter"].append(wdl[2])
                        data["Move"].append(move.uci())
                        data["MoveNr"].append(ply//2)
                        evalBefore = cp
                        wdlBefore = wdl
                gameID += 1
    df = pl.DataFrame(data)
    return df


def getExpectedScoreDropsPerMove(df: pl.DataFrame, xsdWidth: float = 0.1) -> dict:
    """
    This function calculates the number of different expected score drops for each move in the DataFrame
    df: pl.DataFrame
        DataFrame generated by getMoveData
    xsdWidth: float
        Width of the groups for the expected score drop
    return -> dict
        Indexed by expected score drop, containing the number of moves as values
    """
    drops = dict()
    xsFunction = functions.expectedScore
    for row in df.rows(named=True):
        factor = 1 if row["Color"] else -1
        drop = (xsFunction(row["EvalBefore"]) - xsFunction(row["EvalAfter"])) * factor
        drop = (max(0, drop) + xsdWidth/2) // xsdWidth * xsdWidth

        if drop in drops:
            drops[drop] += 1
        else:
            drops[drop] = 1
        
    return drops


def getExpectedScoreDropsPerGame(df: pl.DataFrame, xsdWidth: float = 0.5) -> dict:
    """
    This function calculates teh average number of expected score drops per move per game
    df: pl.DataFrame
        DataFrame generated by getMoveData
    xsdWidth: float
        Width of the groups for the average expected score drop
    return -> dict
        Indexed by average expected score drop per game, containing the number of games
    """
    gameDrops = dict()
    gameID = None
    gameAvg = [[0, 0], [0, 0]]
    xsFunction = functions.expectedScore
    for row in df.rows(named=True):
        if gameID is None:
            gameID = row["GameID"]

        if gameID != row["GameID"]:
            gameID = row["GameID"]
            for i in range(2):
                if gameAvg[i][1] != 0:
                    avgDrop = gameAvg[i][0] / gameAvg[i][1]
                    avgDrop = (avgDrop + xsdWidth/2) // xsdWidth * xsdWidth
                    if avgDrop in gameDrops:
                        gameDrops[avgDrop] += 1
                    else:
                        gameDrops[avgDrop] = 1

                gameAvg = [[0, 0], [0, 0]]

        factor = 1 if row["Color"] else -1
        drop = (xsFunction(row["EvalBefore"]) - xsFunction(row["EvalAfter"])) * factor
        drop = max(0, drop)

        index = max(factor, 0)
        gameAvg[index][0] += drop
        gameAvg[index][1] += 1

    for i in range(2):
        if gameAvg[i][1] != 0:
            avgDrop = gameAvg[i][0] / gameAvg[i][1]
            avgDrop = (avgDrop + xsdWidth/2) // xsdWidth * xsdWidth
            if avgDrop in gameDrops:
                gameDrops[avgDrop] += 1
            else:
                gameDrops[avgDrop] = 1

    return gameDrops


def lichessAccuracy(expectedScoreDrop: float):
    return functions.accuracy(expectedScoreDrop, 0)/100


if __name__ == '__main__':
    carlsen = ['../out/carlsenClassicalAnalysed.pgn']
    pgns = ['../out/games/2700games2023-out.pgn', '../out/games/olympiad2024-out.pgn', '../out/games/grenkeOpen2024.pgn', '../out/games/wijkMasters2024-5000-30.pgn', '../out/games/shenzhen-5000-30.pgn', '../out/games/norwayChessClassical.pgn', '../out/games/candidates2024-WDL+CP.pgn', '../out/games/tepe-sigeman-5000-30.pgn', '../out/games/gukesh2022-out.pgn', '../out/games/Norway2021-classical.pgn', '../out/games/arjun_open-5000-30.pgn', '../out/games/bundesliga2500-out.pgn', '../out/games/candidates2026_analysed.pgn', '../out/games/candidatesW2026_analysed.pgn']
    testScores = [0, 50, 75, 100, 125, 150, 175, 200, 225, 250]
    testScores2 = [0, 0, 0, 0, 0, 0, 0, 0, 0, 250]
    testScores = [20, -20, 40, -30, -40, -60, -30, -30, -20, -30, 0, 0, 50, 20, 110, 140, 370, 200, 280, 180, 240, 100, 100, -10, 10, 20, 120, 70, 340, 10, 300, 100, 170, 180, 150, 160, 190, -80, 0, 0, 0, -30, 20, -50, 140, 30, 40, -140, -80, -160, -200, -180, -120, -90, -20, -150, -140, -120, -40, -260, -240, -260, -260, -570, -560, -550, -520, -510, -450, -470, -440, -420, -370, -420, -380, -430, -450, -430, -430, -490, -480, -500, -440]
    print(functions.lichessGameAccuracy(testScores))
    # df = getMoveData(pgns)
    # df.write_parquet('../out/classicalDF.parquet')
    """
    df = pl.read_parquet('../out/classicalDF.parquet')
    print(df)
    groupWidth = 0.2
    drops = getExpectedScoreDropsPerMove(df, xsdWidth=groupWidth)
    drops = dict(sorted(drops.items()))
    total = sum(list(drops.values()))
    drops = {k: v/total for k, v in drops.items()}
    distributionFunction = {k: 1-sum(list(drops.values())[:i+1]) for i, k in enumerate(list(drops.keys()))}
    """
    # gameDrops = getExpectedScoreDropsPerGame(df, groupWidth)
    # plotting_helper.plotLineChart([list(distributionFunction.keys())], [list(distributionFunction.values())], 'Expected score drop', 'Relative number of moves', 'Move accuracy', legend=['My data', 'Lichess'], refFunction=lichessAccuracy)
    # plotting_helper.plotDistribution(list(drops.keys())[1:], list(drops.values())[1:], groupWidth, 'Expected score drop', 'Number of moves', 'Expected score drops', xMax=80, referenceFunction=lichessAccuracy, logScale=True)
    # plotting_helper.plotDistribution(list(gameDrops.keys()), list(gameDrops.values()), groupWidth, 'Expected score drop', 'Number of games', 'Avg expected score drop')
