Assaubayeva, Bibisara:
- 2439
- 2457
Divya Deshmukh:
- 2416
- 2351
Goryachkina, Aleksandra:
- 2499
- 2424
Lagno, Kateryna:
- 2435
- 2414
Muzychuk, Anna:
- 2398
- 2400
Tan, Zhongyi:
- 2502
- 2424
Vaishali, Rameshbabu:
- 2387
- 2371
Zhu, Jiner:
- 2479
- 2411

