Bluebaum, Matthias:
- 0
- 11
- 1
Caruana, Fabiano:
- 3
- 6
- 3
Esipenko, Andrey:
- 0
- 9
- 3
Giri, Anish:
- 3
- 8
- 1
Nakamura, Hikaru:
- 1
- 9
- 2
Praggnanandhaa R:
- 1
- 8
- 3
Sindarov, Javokhir:
- 6
- 6
- 0
Wei, Yi:
- 1
- 9
- 2

