Assaubayeva, Bibisara:
- 3
- 7
- 2
Divya Deshmukh:
- 2
- 6
- 4
Goryachkina, Aleksandra:
- 1
- 9
- 2
Lagno, Kateryna:
- 3
- 5
- 4
Muzychuk, Anna:
- 2
- 9
- 1
Tan, Zhongyi:
- 1
- 7
- 4
Vaishali, Rameshbabu:
- 4
- 6
- 2
Zhu, Jiner:
- 5
- 4
- 3

