Assaubayeva, Bibisara:
- 4
- 7
- 2
Divya Deshmukh:
- 2
- 6
- 5
Goryachkina, Aleksandra:
- 2
- 9
- 2
Lagno, Kateryna:
- 4
- 5
- 4
Muzychuk, Anna:
- 2
- 9
- 2
Tan, Zhongyi:
- 1
- 8
- 4
Vaishali, Rameshbabu:
- 4
- 7
- 2
Zhu, Jiner:
- 5
- 4
- 4

