- - Sindarov, Javokhir
  - Esipenko, Andrey
- - Bluebaum, Matthias
  - Wei, Yi
- - Praggnanandhaa R
  - Giri, Anish
- - Caruana, Fabiano
  - Nakamura, Hikaru
- - Esipenko, Andrey
  - Nakamura, Hikaru
- - Giri, Anish
  - Caruana, Fabiano
- - Wei, Yi
  - Praggnanandhaa R
- - Sindarov, Javokhir
  - Bluebaum, Matthias
- - Bluebaum, Matthias
  - Esipenko, Andrey
- - Praggnanandhaa R
  - Sindarov, Javokhir
- - Caruana, Fabiano
  - Wei, Yi
- - Nakamura, Hikaru
  - Giri, Anish
- - Esipenko, Andrey
  - Giri, Anish
- - Wei, Yi
  - Nakamura, Hikaru
- - Sindarov, Javokhir
  - Caruana, Fabiano
- - Bluebaum, Matthias
  - Praggnanandhaa R
- - Praggnanandhaa R
  - Esipenko, Andrey
- - Caruana, Fabiano
  - Bluebaum, Matthias
- - Nakamura, Hikaru
  - Sindarov, Javokhir
- - Giri, Anish
  - Wei, Yi
- - Caruana, Fabiano
  - Esipenko, Andrey
- - Nakamura, Hikaru
  - Praggnanandhaa R
- - Giri, Anish
  - Bluebaum, Matthias
- - Wei, Yi
  - Sindarov, Javokhir
- - Esipenko, Andrey
  - Wei, Yi
- - Sindarov, Javokhir
  - Giri, Anish
- - Bluebaum, Matthias
  - Nakamura, Hikaru
- - Praggnanandhaa R
  - Caruana, Fabiano
- - Esipenko, Andrey
  - Sindarov, Javokhir
- - Wei, Yi
  - Bluebaum, Matthias
- - Giri, Anish
  - Praggnanandhaa R
- - Nakamura, Hikaru
  - Caruana, Fabiano
- - Nakamura, Hikaru
  - Esipenko, Andrey
- - Caruana, Fabiano
  - Giri, Anish
- - Praggnanandhaa R
  - Wei, Yi
- - Bluebaum, Matthias
  - Sindarov, Javokhir
- - Esipenko, Andrey
  - Bluebaum, Matthias
- - Sindarov, Javokhir
  - Praggnanandhaa R
- - Wei, Yi
  - Caruana, Fabiano
- - Giri, Anish
  - Nakamura, Hikaru
- - Giri, Anish
  - Esipenko, Andrey
- - Nakamura, Hikaru
  - Wei, Yi
- - Caruana, Fabiano
  - Sindarov, Javokhir
- - Praggnanandhaa R
  - Bluebaum, Matthias
- - Esipenko, Andrey
  - Praggnanandhaa R
- - Bluebaum, Matthias
  - Caruana, Fabiano
- - Sindarov, Javokhir
  - Nakamura, Hikaru
- - Wei, Yi
  - Giri, Anish
- - Wei, Yi
  - Esipenko, Andrey
- - Giri, Anish
  - Sindarov, Javokhir
- - Nakamura, Hikaru
  - Bluebaum, Matthias
- - Caruana, Fabiano
  - Praggnanandhaa R
- - Esipenko, Andrey
  - Caruana, Fabiano
- - Praggnanandhaa R
  - Nakamura, Hikaru
- - Bluebaum, Matthias
  - Giri, Anish
- - Sindarov, Javokhir
  - Wei, Yi

