Bluebaum, Matthias:
- 0
- 12
- 1
Caruana, Fabiano:
- 3
- 7
- 3
Esipenko, Andrey:
- 0
- 9
- 4
Giri, Anish:
- 3
- 9
- 1
Nakamura, Hikaru:
- 1
- 10
- 2
Praggnanandhaa R:
- 1
- 9
- 3
Sindarov, Javokhir:
- 6
- 7
- 0
Wei, Yi:
- 2
- 9
- 2

